[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --alluredir=allure-results
    --tb=short
markers =
    smoke: Marks tests as smoke tests
    regression: Marks tests as regression tests
    auth: Marks tests related to authentication
    users: Marks tests related to user management
